### ISSUE TITLE
Kindly request the code for running baseline models.

### ISSUE THREAD

**Issue by Tebmer** [YebowenHu/SportsMetrics#1]
Hi, Yebowen,

That's an awesome work and thanks for your open source of metrics code!  

I would like to kindly ask whether the code for running baselines could be open-source? If so, the following works could reproduce your paper more conveniently and expand your paper's influence in a further way. :) 

Thanks for your continuous effort in open-source, and I appreciate it greatly!

**Comment by Tebmer** [comment]
Oh! I just found it in evaluation_sample.py. Sorry for such a stupid question..

**Comment by YebowenHu** [comment]
Thanks for your interest in SportsMetrics. The script to use the OpenAI model is uploaded. Feel free to implement your local LLMs to run this benchmark.
